# Generated by Django 5.0.7 on 2024-10-07 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cup/', verbose_name='лого кубка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asdasd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'кубок',
                'verbose_name_plural': 'кубки',
            },
        ),
    ]
