# Generated by Django 5.0.7 on 2024-10-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='cups',
            field=models.ManyToManyField(blank=True, to='users.cup', verbose_name='кубки команды'),
        ),
    ]
