# Generated by Django 5.0.7 on 2024-10-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_cup_user_user_cups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='имя'),
        ),
    ]
