# Generated by Django 4.2.7 on 2024-03-30 09:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_POKER_tournament_no_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='дата')),
                ('is_on', models.BooleanField(default=False, verbose_name='одобренно')),
            ],
            options={
                'verbose_name': 'заявки на турниры',
                'verbose_name_plural': 'тзаявки на турниры',
            },
        ),
        migrations.CreateModel(
            name='match_POKER',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('time_hour', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='время начала в часах')),
                ('time_minutes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)], verbose_name='время начала в минутах')),
                ('price_match', models.IntegerField(default=0, null=True, verbose_name='призовой фонд')),
            ],
            options={
                'verbose_name': 'матч_POKER',
                'verbose_name_plural': 'матчи_POKER',
            },
        ),
    ]
