# Generated by Django 4.2.7 on 2024-03-30 09:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_POKER',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='дата присоединения')),
                ('matches', models.IntegerField(default=0, verbose_name='кол-во матчей')),
                ('win_matches', models.IntegerField(default=0, verbose_name='кол-во побед матчи')),
                ('tournament', models.IntegerField(default=0, verbose_name='кол-во турниров')),
                ('win_tournament', models.IntegerField(default=0, verbose_name='кол-во побед турнир')),
                ('is_recognized', models.BooleanField(default=False, verbose_name='признанный игрок')),
            ],
            options={
                'verbose_name': 'Игрок_POKER',
                'verbose_name_plural': 'Игроки_POKER',
            },
        ),
        migrations.CreateModel(
            name='tournament_POKER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название турнира')),
                ('price_tournament', models.IntegerField(default=0, null=True, verbose_name='призовой фонд')),
                ('data', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('time_hour', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(23)], verbose_name='время начала в часах')),
                ('time_minutes', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59)], verbose_name='время начала в минутах')),
                ('matches', models.ManyToManyField(blank=True, to='poker.match_poker', verbose_name='матчи турнира')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_tournament_POKER', to=settings.AUTH_USER_MODEL)),
                ('player', models.ManyToManyField(blank=True, related_name='team_POKER_playy', to='poker.player_poker', verbose_name='участники')),
                ('win_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='POKER_win_tournament', to='poker.player_poker')),
            ],
            options={
                'verbose_name': 'турнир_POKER',
                'verbose_name_plural': 'турниры_POKER',
            },
        ),
        migrations.AddField(
            model_name='match_poker',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation_match_POKER', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match_poker',
            name='player',
            field=models.ManyToManyField(blank=True, related_name='team_POKER_play', to='poker.player_poker', verbose_name='участники'),
        ),
        migrations.AddField(
            model_name='match_poker',
            name='win',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_POKER_win', to='poker.player_poker'),
        ),
        migrations.AddField(
            model_name='application_poker_tournament_no_team',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dire2ctor_zx3cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
