# Generated by Django 4.2.7 on 2024-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_record_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_stat',
            name='blockshot',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='point',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='rebound',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='shot',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='shot_relize',
        ),
        migrations.AddField(
            model_name='record_stat',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='ассисты'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='damage',
            field=models.IntegerField(default=0, verbose_name='урон'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='death',
            field=models.IntegerField(default=0, verbose_name='смерти'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='kill',
            field=models.IntegerField(default=0, verbose_name='убийства'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='win',
            field=models.BooleanField(default=False, verbose_name='победа'),
        ),
        migrations.AddField(
            model_name='team_cs',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='ассисты'),
        ),
        migrations.AddField(
            model_name='team_cs',
            name='death',
            field=models.IntegerField(default=0, verbose_name='смерти'),
        ),
        migrations.AddField(
            model_name='team_cs',
            name='kill',
            field=models.IntegerField(default=0, verbose_name='убийства'),
        ),
    ]
