# Generated by Django 5.0.7 on 2024-10-08 09:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='ранг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rank/', verbose_name='картинка ранга')),
            ],
            options={
                'verbose_name': 'ранг',
                'verbose_name_plural': 'ранги',
            },
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='clown`s', max_length=30, unique=True, verbose_name='название команды')),
                ('logo', models.ImageField(blank=True, default='/team/logo/default.png', null=True, upload_to='team/logo/', verbose_name='лого команды')),
                ('background', models.ImageField(blank=True, default='/team/background/default.png', null=True, upload_to='team/background/', verbose_name='фон')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='статус')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='подробно')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('is_recognized', models.BooleanField(default=False, verbose_name='признанная команда')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ection21_12', to='direction.direction')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
            },
        ),
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=False, verbose_name='просмотр')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('matches_in_offers', models.IntegerField(default=10, verbose_name='кол-во матчей в контракте')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ecti1on_12', to='direction.direction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unification.team')),
            ],
            options={
                'verbose_name': 'оффер',
                'verbose_name_plural': 'офферы',
            },
        ),
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friends', models.BooleanField(default=True, verbose_name='дружеский')),
                ('is_qualification', models.BooleanField(default=False, verbose_name='квалификация')),
                ('team_one_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды один')),
                ('team_two_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды два')),
                ('team_one_ball', models.IntegerField(blank=True, default=0, null=True, verbose_name='баллы команды один')),
                ('team_two_ball', models.IntegerField(blank=True, default=0, null=True, verbose_name='баллы команды два')),
                ('date', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('countmatch', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='b0')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ec123tion21_12', to='direction.direction')),
                ('team_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_meeting_one', to='unification.team')),
                ('team_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_meeting_two', to='unification.team')),
                ('win_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_meeting_win', to='unification.team')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
            },
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='20:00', verbose_name='время начала')),
                ('date', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('team_one_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды один')),
                ('team_two_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды два')),
                ('id_match', models.IntegerField(default=0, verbose_name='ид матча')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ec12123tion21_12', to='direction.direction')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unification.meeting')),
                ('team_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_match_one', to='unification.team')),
                ('team_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_match_two', to='unification.team')),
                ('win_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_match_win', to='unification.team')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
            },
        ),
        migrations.CreateModel(
            name='cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cup/', verbose_name='лого кубка')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asdasd', to='unification.team')),
            ],
            options={
                'verbose_name': 'кубок',
                'verbose_name_plural': 'кубки',
            },
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='название')),
                ('about', models.CharField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('date', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('is_on', models.BooleanField(default=False, verbose_name='закрыт')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('price_tournament', models.IntegerField(blank=True, null=True, verbose_name='призовой фонд')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ec123tion21_1fsg2', to='direction.direction')),
                ('teams', models.ManyToManyField(blank=True, related_name='team_DOTA_play', to='unification.team', verbose_name='команды-участники')),
                ('win_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_DOTA_w12in_tournament', to='unification.team')),
            ],
            options={
                'verbose_name': 'турнир',
                'verbose_name_plural': 'турниры',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unification.tournament'),
        ),
    ]
