# Generated by Django 5.0.7 on 2024-10-11 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
        ('unification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('is_on', models.BooleanField(default=False, verbose_name='одобренно')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dir124ec123dastion21_12', to='direction.direction')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_applicat412ion_tournament', to='unification.team')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_a123pplication_tournament', to='unification.tournament')),
            ],
            options={
                'verbose_name': 'заявка на турнир',
                'verbose_name_plural': 'заявки на турниры',
            },
        ),
    ]
