# Generated by Django 5.0.7 on 2024-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unification', '0002_application_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='cups',
            field=models.ManyToManyField(blank=True, to='unification.cup', verbose_name='кубки команды'),
        ),
    ]
