# Generated by Django 5.0.7 on 2024-10-13 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unification', '0003_remove_cup_team_team_cups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='name')),
                ('team_cs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asdasd2t4e24', to='unification.team')),
                ('team_dota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unification.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'игрок',
                'verbose_name_plural': 'игрок',
            },
        ),
    ]
