# Generated by Django 5.0.7 on 2024-10-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unification', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank_cs',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adsawegtsdasd', to='unification.rank'),
        ),
        migrations.AddField(
            model_name='player',
            name='rank_dota',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adsaasdasddasd', to='unification.rank'),
        ),
    ]
