# Generated by Django 4.2.7 on 2024-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_name', models.CharField(default='clown', max_length=30, verbose_name='название состава')),
            ],
            options={
                'verbose_name': 'состав',
                'verbose_name_plural': 'составы',
            },
        ),
    ]
