# Generated by Django 4.2.7 on 2024-03-30 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='контент')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='дата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/image/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
