# Generated by Django 5.0.7 on 2024-10-07 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('content', models.CharField(max_length=255, verbose_name='на что')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'трата',
                'verbose_name_plural': 'траты',
            },
        ),
        migrations.CreateModel(
            name='list_cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, verbose_name='бюджет')),
            ],
            options={
                'verbose_name': 'бюджет',
                'verbose_name_plural': 'бюджет',
            },
        ),
    ]
