# Generated by Django 4.2.7 on 2024-04-11 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction', '0001_initial'),
        ('cash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cash',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='direction.direction'),
        ),
    ]
