# Generated by Django 4.2.7 on 2024-04-11 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='сценaрий')),
            ],
            options={
                'verbose_name': 'сценарий',
                'verbose_name_plural': 'сценарии',
            },
        ),
        migrations.CreateModel(
            name='transfer_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'трансферы_BASCKETBALL',
                'verbose_name_plural': 'трансферы_BASCKETBALL',
            },
        ),
        migrations.CreateModel(
            name='transfer_CS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'трансферы_CS',
                'verbose_name_plural': 'трансферы_CS',
            },
        ),
        migrations.CreateModel(
            name='transfer_DOTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания')),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfers.script')),
            ],
            options={
                'verbose_name': 'трансферы_DOTA',
                'verbose_name_plural': 'трансферы_DOTA',
            },
        ),
    ]
