# Generated by Django 5.0.7 on 2024-10-07 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        ('unification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='unification.team'),
        ),
    ]
