# Generated by Django 4.2.7 on 2024-03-30 09:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_BASCKETBALL_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('is_accept', models.BooleanField(default=False, verbose_name='одобренно командой')),
                ('is_on', models.BooleanField(default=False, verbose_name='одобренно')),
                ('matches', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='b0')),
                ('time1', models.TimeField(default='18:00', verbose_name='время начала')),
                ('time2', models.TimeField(default='18:00', verbose_name='время начала')),
            ],
            options={
                'verbose_name': 'вызов на матчи',
                'verbose_name_plural': 'вызовы на матчи',
            },
        ),
        migrations.CreateModel(
            name='application_BASCKETBALL_tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('is_on', models.BooleanField(default=False, verbose_name='одобренно')),
            ],
            options={
                'verbose_name': 'заявки на турниры',
                'verbose_name_plural': 'заявки на турниры',
            },
        ),
        migrations.CreateModel(
            name='cup_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cup/basketball/', verbose_name='лого кубка')),
            ],
            options={
                'verbose_name': 'кубок_комады',
                'verbose_name_plural': 'кубки_команды',
            },
        ),
        migrations.CreateModel(
            name='generation_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_name', models.CharField(default='clown', max_length=30, verbose_name='название состава')),
            ],
            options={
                'verbose_name': 'состав',
                'verbose_name_plural': 'составы',
            },
        ),
        migrations.CreateModel(
            name='match_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('team_one_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды один')),
                ('team_two_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды два')),
                ('id_match', models.IntegerField(default=0, verbose_name='ид матча')),
                ('time', models.TimeField(default='20:00', verbose_name='время начала')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
            },
        ),
        migrations.CreateModel(
            name='meeting_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_friends', models.BooleanField(default=True, verbose_name='дружеский')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('team_one_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды один')),
                ('team_two_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='счет команды два')),
                ('is_qualification', models.BooleanField(default=False, verbose_name='квалификация')),
                ('team_one_ball', models.IntegerField(blank=True, default=0, null=True, verbose_name='баллы команды один')),
                ('team_two_ball', models.IntegerField(blank=True, default=0, null=True, verbose_name='баллы команды два')),
                ('date', models.DateField(blank=True, null=True, verbose_name='датa')),
                ('matches', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='b0')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
            },
        ),
        migrations.CreateModel(
            name='offers_BASCKETBALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_view', models.BooleanField(default=False, verbose_name='согласие пользователя')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('matches_in_offers', models.IntegerField(default=1, verbose_name='кол-во матчей в контракте')),
            ],
            options={
                'verbose_name': 'оффер',
                'verbose_name_plural': 'офферы',
            },
        ),
    ]
