# Generated by Django 4.2.7 on 2024-04-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bascketball', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_stat',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teame1BASCKETBALLe_DOTA_onesdqw', to='bascketball.match_bascketball'),
        ),
    ]
