# Generated by Django 4.2.7 on 2024-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bascketball', '0003_alter_record_stat_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_stat',
            name='win',
            field=models.BooleanField(default=False, verbose_name='победа'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='blockshot',
            field=models.IntegerField(default=0, verbose_name='блокшоты'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='passage',
            field=models.IntegerField(default=0, verbose_name='проходы'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='point',
            field=models.IntegerField(default=0, verbose_name='очки'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='rebound',
            field=models.IntegerField(default=0, verbose_name='подборы'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='shot',
            field=models.IntegerField(default=0, verbose_name='броски'),
        ),
        migrations.AddField(
            model_name='team_bascketball',
            name='shot_relize',
            field=models.IntegerField(default=0, verbose_name='броски_попадания'),
        ),
    ]
