# Generated by Django 4.2.7 on 2024-04-11 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dota', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebound', models.IntegerField(default=0, verbose_name='подборы')),
                ('shot', models.IntegerField(default=0, verbose_name='броски')),
                ('point', models.IntegerField(default=0, verbose_name='очки')),
                ('shot_relize', models.IntegerField(default=0, verbose_name='броски_попадания')),
                ('passage', models.IntegerField(default=0, verbose_name='проходы')),
                ('blockshot', models.IntegerField(default=0, verbose_name='блокшоты')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teameqdw1BASCKETBALLe_DOTA_onesdqw', to='dota.match_dota')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teame1BASCKETBAL123Le_DOTA_onedwsads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'статистика игрока',
                'verbose_name_plural': 'статистики игроков',
            },
        ),
    ]
