# Generated by Django 4.2.7 on 2024-04-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0003_record_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(default='clown`s', max_length=45, unique=True, verbose_name='имя героя')),
            ],
            options={
                'verbose_name': 'герой',
                'verbose_name_plural': 'герои',
            },
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='blockshot',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='passage',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='point',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='rebound',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='shot',
        ),
        migrations.RemoveField(
            model_name='record_stat',
            name='shot_relize',
        ),
        migrations.AddField(
            model_name='record_stat',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='ассисты'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='damage',
            field=models.IntegerField(default=0, verbose_name='урон'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='damage_t',
            field=models.IntegerField(default=0, verbose_name='урон башням'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='death',
            field=models.IntegerField(default=0, verbose_name='смерти'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='heal',
            field=models.IntegerField(default=0, verbose_name='хил'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='kill',
            field=models.IntegerField(default=0, verbose_name='убийства'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='win',
            field=models.BooleanField(default=False, verbose_name='победа'),
        ),
        migrations.AddField(
            model_name='team_dota',
            name='assist',
            field=models.IntegerField(default=0, verbose_name='ассисты'),
        ),
        migrations.AddField(
            model_name='team_dota',
            name='death',
            field=models.IntegerField(default=0, verbose_name='смерти'),
        ),
        migrations.AddField(
            model_name='team_dota',
            name='kill',
            field=models.IntegerField(default=0, verbose_name='убийства'),
        ),
        migrations.AddField(
            model_name='record_stat',
            name='hero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teameqdw1BASCKETBALLe_DOTA_onesdqw12', to='dota.hero'),
        ),
    ]
