# Generated by Django 4.2.7 on 2024-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0004_hero_remove_record_stat_blockshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='dota/hero/', verbose_name='картинка героя'),
        ),
    ]
