# Generated by Django 4.2.7 on 2024-04-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0006_record_stat_first_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_stat',
            name='gold',
            field=models.IntegerField(default=0, verbose_name='золото'),
        ),
    ]
